name: ModelOps (Build, Deploy)
# Requires GitHub Action Secrets: AZURE_WEBAPP_NAME, AZURE_WEBAPP_PUBLISH_PROFILE

on:
    workflow_dispatch:
    workflow_run:
      workflows: ["ModelOps (Update Model)"]
      types:
        - completed

permissions:
  packages: write      

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
          
          - name: Log in to GitHub container registry
            uses: docker/login-action@v1.10.0
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
          
          - name: Lowercase the repo name and username
            run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          
          - name: Build and push container image to registry
            uses: docker/build-push-action@v2
            with:
                context: .
                push: true
                tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
                file: C:\Users\danie\MDM\projekt1-bike-scraper\src\Dockerfile 

    deploy:
      needs: build  
      runs-on: ubuntu-latest
          
      steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      
      - name: Deploy to Azure Web App using Publish Profile
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
              app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
              publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
              images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
