name: Build and deploy container app to Azure Web App - tuttibikes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: brodydan.azurecr.io
          username: ${{ secrets.AzureAppService_ContainerUsername_66b04f444346491cb81eced96c3cc06d }}
          password: ${{ secrets.AzureAppService_ContainerPassword_31bb27f4ff9a49648868f3baa7fab7dc }}

      # Build and push the Docker image to ACR
      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: brodydan.azurecr.io/tuttibikes:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Deploy the Docker image to Azure App Service
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tuttibikes'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_2145659d6c15419b8ee670dffe53d5aa }}
          images: 'brodydan.azurecr.io/tuttibikes:${{ github.sha }}'