# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tuttibikes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://brodydan.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_66b04f444346491cb81eced96c3cc06d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_31bb27f4ff9a49648868f3baa7fab7dc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: brodydan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_66b04f444346491cb81eced96c3cc06d }}/tuttibikes:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tuttibikes'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2145659d6c15419b8ee670dffe53d5aa }}
        images: 'brodydan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_66b04f444346491cb81eced96c3cc06d }}/tuttibikes:${{ github.sha }}'